# Generated by Django 2.2.6 on 2020-02-25 22:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='FinalOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.IntegerField(choices=[(1, 'COD'), (2, 'PayPal')], null=True)),
                ('overall_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True)),
                ('trans_id', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=0)),
                ('delivery_date', models.DateTimeField(null=True)),
                ('delivered_date', models.DateTimeField(null=True)),
                ('status', models.IntegerField(choices=[(1, 'Packaging'), (2, 'In Transit'), (3, 'Out for Delivery'), (4, 'Validation')], default=4, null=True)),
                ('final_order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='api_proc.FinalOrder')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_image', models.ImageField(null=True, upload_to='')),
                ('product_image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('product_image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('stock', models.IntegerField(null=True)),
                ('delivery_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('views', models.PositiveIntegerField(null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api_proc.Category')),
                ('sale', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'unique_together': {('product_name', 'category', 'price')},
            },
        ),
        migrations.CreateModel(
            name='InitialOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_proc.Product')),
            ],
        ),
        migrations.AddField(
            model_name='finalorder',
            name='orders',
            field=models.ManyToManyField(to='api_proc.InitialOrder'),
        ),
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('middle_initial', models.CharField(blank=True, max_length=3)),
                ('contact_number', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('date_ordered', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('payment_method', models.IntegerField(choices=[(1, 'COD'), (2, 'PayPal')])),
                ('final_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_proc.FinalOrder')),
            ],
        ),
    ]

