# Generated by Django 2.1.7 on 2019-09-01 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('middle_initial', models.CharField(blank=True, max_length=3, null=True)),
                ('contact_number', models.TextField()),
                ('delivery_date', models.DateTimeField()),
                ('delivered_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FinalOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InitialOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_image', models.ImageField(null=True, upload_to='')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('stock', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='initialorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_proc.Product'),
        ),
        migrations.AddField(
            model_name='finalorder',
            name='orders',
            field=models.ManyToManyField(to='api_proc.InitialOrder'),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='final_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_proc.FinalOrder'),
        ),
    ]
