# Generated by Django 2.2.6 on 2020-02-25 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_proc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sale',
        ),
    ]
