# Generated by Django 2.2.6 on 2020-02-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_proc', '0002_remove_product_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
