# Generated by Django 2.1.7 on 2019-10-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_proc', '0002_auto_20190904_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
