# Generated by Django 2.1.7 on 2019-10-01 12:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_proc', '0003_auto_20191001_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('delivery_date', models.DateTimeField()),
                ('delivered_date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='delivered_date',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='delivery_date',
        ),
        migrations.AddField(
            model_name='transaction',
            name='costumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_proc.CustomerInfo'),
        ),
    ]
