# Generated by Django 2.2.6 on 2020-03-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_proc', '0003_product_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='views',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
