# Generated by Django 2.1.7 on 2019-10-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_proc', '0004_auto_20191001_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalorder',
            name='overall_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
