# Generated by Django 2.1.7 on 2019-10-02 09:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_proc', '0005_finalorder_overall_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalorder',
            name='trans_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
