# Generated by Django 2.2.6 on 2020-03-04 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_proc', '0006_auto_20200304_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='final_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api_proc.FinalOrder'),
        ),
    ]
