# Generated by Django 2.1.7 on 2019-10-02 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_proc', '0006_finalorder_trans_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='costumer',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='trans_id',
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='email',
            field=models.EmailField(default='none@testmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='payment_method',
            field=models.IntegerField(default=0, verbose_name=((0, 'not_set'), (1, 'COD'), (2, 'PayPal'))),
        ),
        migrations.AddField(
            model_name='transaction',
            name='final_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_proc.FinalOrder'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paid',
            field=models.BooleanField(default=0),
        ),
    ]
