# Generated by Django 2.1.7 on 2019-10-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_proc', '0007_auto_20191003_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='payment_method',
            field=models.IntegerField(null=True, verbose_name=((1, 'COD'), (2, 'PayPal'))),
        ),
    ]
