# Generated by Django 2.1.7 on 2019-10-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_proc', '0008_auto_20191003_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
