# Generated by Django 2.1.7 on 2019-10-03 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_proc', '0009_auto_20191003_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 17, 57, 35, 691002), editable=False),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
