# Generated by Django 2.1.7 on 2019-10-03 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_proc', '0010_auto_20191003_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 18, 7, 57, 908769), editable=False),
        ),
    ]
