# Generated by Django 2.1.7 on 2019-10-03 11:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api_proc', '0011_auto_20191003_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 11, 5, 45, 776004, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='delivered_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='delivery_date',
            field=models.DateTimeField(null=True),
        ),
    ]
