# Generated by Django 2.2.6 on 2019-10-07 15:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api_proc', '0012_auto_20191003_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 7, 15, 1, 4, 76510, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='views',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
