# Generated by Django 2.2.6 on 2019-10-07 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_proc', '0013_auto_20191007_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='date_ordered',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
