# Generated by Django 2.2.6 on 2020-01-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_proc', '0016_auto_20191010_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
