# Generated by Django 2.2.6 on 2020-01-14 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_proc', '0017_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(null=True, verbose_name=((1, 'Packaging'), (2, 'In Transit'), (3, 'Out for Delivery')))),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_proc.Transaction')),
            ],
        ),
    ]
