# Generated by Django 2.2.6 on 2020-01-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_proc', '0018_deliverystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(null=True, verbose_name=((1, 'Packaging'), (2, 'In Transit'), (3, 'Out for Delivery'))),
        ),
        migrations.DeleteModel(
            name='DeliveryStatus',
        ),
    ]
