# Generated by Django 2.2.6 on 2020-01-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_proc', '0019_auto_20200122_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(max_length=2, null=True, verbose_name=(('P', 'Packaging'), ('T', 'In Transit'), ('D', 'Out for Delivery'))),
        ),
    ]
