# Generated by Django 2.2.6 on 2020-01-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_proc', '0021_auto_20200122_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(max_length=20, null=True, verbose_name=('Packaging', 'In Transit', 'Out for Delivery')),
        ),
    ]
