# Generated by Django 2.2.6 on 2020-01-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_proc', '0023_auto_20200122_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(choices=[(1, 'Packaging'), (2, 'In Transit'), (3, 'Out for Delivery')], max_length=20, null=True),
        ),
    ]
