# Generated by Django 2.2.6 on 2020-01-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_proc', '0024_auto_20200122_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'COD'), (2, 'PayPal')], null=True),
        ),
    ]
