# Generated by Django 2.2.6 on 2020-01-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_proc', '0029_auto_20200122_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'COD'), (2, 'PayPal')], default=1),
        ),
    ]
