# Generated by Django 2.2.6 on 2020-02-20 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_proc', '0031_auto_20200122_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='final_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_proc.FinalOrder'),
        ),
        migrations.AlterField(
            model_name='initialorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_proc.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api_proc.Category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='final_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='api_proc.FinalOrder'),
        ),
    ]
