# Generated by Django 2.2.6 on 2020-02-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_proc', '0032_auto_20200220_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
