# Generated by Django 2.2.6 on 2020-02-20 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_proc', '0033_product_hidden'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('product_name', 'category', 'price')},
        ),
    ]
