# Generated by Django 2.2.6 on 2019-10-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_img1', models.ImageField(null=True, upload_to='')),
                ('car_img2', models.ImageField(blank=True, null=True, upload_to='')),
                ('car_img3', models.ImageField(blank=True, null=True, upload_to='')),
                ('about', models.TextField()),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
    ]
