# Generated by Django 2.2.6 on 2020-01-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_ep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontasset',
            name='company_logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='frontasset',
            name='company_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
