# Generated by Django 2.2.6 on 2020-01-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_ep', '0002_auto_20200116_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontasset',
            name='colorscheme',
            field=models.CharField(default='#222222', max_length=7),
        ),
    ]
